import { Question } from '@/lib/supabase/types';

export const MARLINS_60_STANDARD_QUESTIONS: Question[] = [
  // ==========================================
  // SECTION 1: GRAMMAR (15 QUESTIONS)
  // ==========================================
  {
    id: 'marlins-g-01',
    category: 'grammar',
    question_type: 'multiple_choice',
    question_text: 'The Chief Housekeeper _______ the passenger cabins on Deck 7 every morning.',
    options: ['inspects', 'inspecting', 'inspect', 'is inspected'],
    correct_answer: 'inspects',
    order_number: 1,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-g-02',
    category: 'grammar',
    question_type: 'multiple_choice',
    question_text: 'All crew members must _______ their lifejackets during the passenger muster drill.',
    options: ['wear', 'wears', 'wearing', 'wore'],
    correct_answer: 'wear',
    order_number: 2,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-g-03',
    category: 'grammar',
    question_type: 'multiple_choice',
    question_text: 'Choose the correct sentence to describe the ongoing action. (Time indicator: NOW)',
    options: [
      'The waiter is serving dinner to the guests.',
      'The waiter served dinner to the guests yesterday.',
      'The waiter will serve dinner to the guests tomorrow.',
      'The waiter has been served dinner.'
    ],
    correct_answer: 'The waiter is serving dinner to the guests.',
    order_number: 3,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=350&fit=crop',
    pronunciation_text: null,
    question_data: {
      hint: 'Look at the time indicator: NOW (Present Continuous Tense)',
    },
  },
  {
    id: 'marlins-g-04',
    category: 'grammar',
    question_type: 'gap_fill',
    question_text: 'Complete the sentences with the correct auxiliary verbs.',
    correct_answer: 'was,entered',
    order_number: 4,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      text_template: 'The restaurant steward {0} cleaning the buffet area when the Captain {1} the dining room.',
      gaps: [
        { index: 0, correct: 'was', options: ['was', 'were', 'is', 'are'] },
        { index: 1, correct: 'entered', options: ['entered', 'entering', 'enters', 'enter'] },
      ],
    },
  },
  {
    id: 'marlins-g-05',
    category: 'grammar',
    question_type: 'sentence_reorder',
    question_text: 'Arrange the words in the correct order to form a proper crew safety announcement.',
    correct_answer: 'Please keep all emergency fire doors closed',
    order_number: 5,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      words: ['Please', 'keep', 'all', 'emergency', 'fire', 'doors', 'closed'],
      correct_sentence: 'Please keep all emergency fire doors closed',
    },
  },
  {
    id: 'marlins-g-06',
    category: 'grammar',
    question_type: 'multiple_choice',
    question_text: 'Choose the correct sentence to describe the image. (Time indicator: YESTERDAY MORNING)',
    options: [
      'The cruise ship arrived at the port yesterday morning.',
      'The cruise ship is arriving at the port right now.',
      'The cruise ship will arrive at the port tomorrow.',
      'The cruise ship arrives at the port every hour.'
    ],
    correct_answer: 'The cruise ship arrived at the port yesterday morning.',
    order_number: 6,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=350&fit=crop',
    pronunciation_text: null,
    question_data: {
      hint: 'Look at the time indicator: YESTERDAY MORNING (Past Simple Tense)',
    },
  },
  {
    id: 'marlins-g-07',
    category: 'grammar',
    question_type: 'multiple_choice',
    question_text: 'How long _______ you worked as a cabin steward on international cruise liners?',
    options: ['have', 'has', 'did', 'are'],
    correct_answer: 'have',
    order_number: 7,
    is_active: true,
    level: 'B1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-g-08',
    category: 'grammar',
    question_type: 'multiple_choice',
    question_text: 'Safety goggles and gloves _______ be worn when handling chemical sanitizers in the galley.',
    options: ['must', 'might', 'could', 'shall not'],
    correct_answer: 'must',
    order_number: 8,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-g-09',
    category: 'grammar',
    question_type: 'sentence_reorder',
    question_text: 'Arrange the words to form a polite guest service response.',
    correct_answer: 'Would you like me to bring you some extra towels?',
    order_number: 9,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      words: ['Would', 'you', 'like', 'me', 'to', 'bring', 'you', 'some', 'extra', 'towels?'],
      correct_sentence: 'Would you like me to bring you some extra towels?',
    },
  },
  {
    id: 'marlins-g-10',
    category: 'grammar',
    question_type: 'gap_fill',
    question_text: 'Choose the correct prepositions to complete the sentence.',
    correct_answer: 'on,to',
    order_number: 10,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      text_template: 'The muster station is located {0} Deck 5, right next {1} the theater.',
      gaps: [
        { index: 0, correct: 'on', options: ['on', 'in', 'at', 'by'] },
        { index: 1, correct: 'to', options: ['to', 'of', 'from', 'with'] },
      ],
    },
  },
  {
    id: 'marlins-g-11',
    category: 'grammar',
    question_type: 'multiple_choice',
    question_text: 'There _______ enough clean wine glasses at the Lido Bar for the gala dinner tonight.',
    options: ['are not', 'is not', 'was not', 'not have'],
    correct_answer: 'are not',
    order_number: 11,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-g-12',
    category: 'grammar',
    question_type: 'multiple_choice',
    question_text: 'The Officer of the Watch asked the lookout if he _______ any objects on the water.',
    options: ['had spotted', 'has spotted', 'is spotting', 'spot'],
    correct_answer: 'had spotted',
    order_number: 12,
    is_active: true,
    level: 'B1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-g-13',
    category: 'grammar',
    question_type: 'sentence_reorder',
    question_text: 'Rearrange the words to make a proper passenger request to the housekeeping department.',
    correct_answer: 'Could you send someone to repair my bedside lamp?',
    order_number: 13,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      words: ['Could', 'you', 'send', 'someone', 'to', 'repair', 'my', 'bedside', 'lamp?'],
      correct_sentence: 'Could you send someone to repair my bedside lamp?',
    },
  },
  {
    id: 'marlins-g-14',
    category: 'grammar',
    question_type: 'gap_fill',
    question_text: 'Choose the correct prepositions to complete the cruise rules statement.',
    correct_answer: 'at,in,on',
    order_number: 14,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      text_template: 'The ship docks {0} the port {1} the morning. All safety rules apply {2} board.',
      gaps: [
        { index: 0, correct: 'at', options: ['at', 'on', 'to', 'in'] },
        { index: 1, correct: 'in', options: ['in', 'at', 'on', 'of'] },
        { index: 2, correct: 'on', options: ['on', 'in', 'at', 'under'] },
      ],
    },
  },
  {
    id: 'marlins-g-15',
    category: 'grammar',
    question_type: 'multiple_choice',
    question_text: 'Neither the bartender _______ the bar waiter was aware of the spilled drink on the dance floor.',
    options: ['nor', 'or', 'and', 'but'],
    correct_answer: 'nor',
    order_number: 15,
    is_active: true,
    level: 'B1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },

  // ==========================================
  // SECTION 2: VOCABULARY (15 QUESTIONS)
  // ==========================================
  {
    id: 'marlins-v-16',
    category: 'vocabulary',
    question_type: 'drag_drop_label',
    question_text: 'Drag the words to label the objects in the coffee station and uniform image.',
    correct_answer: 'sugar bowl,coffee cup lid,milk carton,waistcoat',
    order_number: 16,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=400&fit=crop',
    pronunciation_text: null,
    question_data: {
      labels: ['sugar bowl', 'coffee cup lid', 'milk carton', 'waistcoat'],
      drop_zones: [
        { id: 'z1', hint: 'Container for sweetening granules', label: 'Container for sugar', correct_label: 'sugar bowl' },
        { id: 'z2', hint: 'Covers the takeaway coffee cup', label: 'Top cover for hot cup', correct_label: 'coffee cup lid' },
        { id: 'z3', hint: 'Carton container containing dairy milk', label: 'Carton with fresh milk', correct_label: 'milk carton' },
        { id: 'z4', hint: 'Sleeveless formal vest worn by server', label: 'Uniform vest garment', correct_label: 'waistcoat' },
      ],
    },
  },
  {
    id: 'marlins-v-17',
    category: 'vocabulary',
    question_type: 'drag_drop_label',
    question_text: 'Drag the words to label the bar tools and drink service accessories shown in the image.',
    correct_answer: 'straw,coaster,strainer,bar measure',
    order_number: 17,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&h=400&fit=crop',
    pronunciation_text: null,
    question_data: {
      labels: ['straw', 'coaster', 'strainer', 'bar measure'],
      drop_zones: [
        { id: 'z1', hint: 'Thin drinking tube for iced drinks', label: 'Drinking tube', correct_label: 'straw' },
        { id: 'z2', hint: 'Small mat placed underneath glass to protect bar', label: 'Protective drink mat', correct_label: 'coaster' },
        { id: 'z3', hint: 'Perforated metal tool to filter ice when pouring cocktail', label: 'Cocktail ice filter', correct_label: 'strainer' },
        { id: 'z4', hint: 'Dual-sided metal cup used to measure spirits (jigger)', label: 'Liquor measuring jigger', correct_label: 'bar measure' },
      ],
    },
  },
  {
    id: 'marlins-v-18',
    category: 'vocabulary',
    question_type: 'drag_drop_label',
    question_text: 'Drag the labels to identify the beverage accessories and ice service tools.',
    correct_answer: 'serving tongs,ice,wine cork,bar spoon',
    order_number: 18,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&h=400&fit=crop',
    pronunciation_text: null,
    question_data: {
      labels: ['serving tongs', 'ice', 'wine cork', 'bar spoon'],
      drop_zones: [
        { id: 'z1', hint: 'Pincer tool used to pick up ice cubes hygienically', label: 'Hygienic ice gripping tool', correct_label: 'serving tongs' },
        { id: 'z2', hint: 'Frozen solid water cubes in the bucket', label: 'Frozen water cubes', correct_label: 'ice' },
        { id: 'z3', hint: 'Stopper removed from a wine bottle', label: 'Bottle stopper', correct_label: 'wine cork' },
        { id: 'z4', hint: 'Long spiral metal spoon for stirring mixed drinks', label: 'Long stirring spoon', correct_label: 'bar spoon' },
      ],
    },
  },
  {
    id: 'marlins-v-19',
    category: 'vocabulary',
    question_type: 'image_choice',
    question_text: 'Which image shows a "Ladle" (deep-bowled spoon used for serving soup and gravy in the galley)?',
    options: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=400&h=400&fit=crop'
    ],
    correct_answer: 'Ladle',
    order_number: 19,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      option_type: 'image',
      option_labels: ['Ladle', 'Whisk', 'Spatula', 'Tongs'],
    },
  },
  {
    id: 'marlins-v-20',
    category: 'vocabulary',
    question_type: 'image_choice',
    question_text: 'Which image shows a standard maritime "Life Jacket / Life Preserver" required in all passenger cabins?',
    options: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=400&fit=crop'
    ],
    correct_answer: 'Life Jacket',
    order_number: 20,
    is_active: true,
    level: 'A1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      option_type: 'image',
      option_labels: ['Life Jacket', 'Rain Coat', 'Galley Apron', 'Officer Blazer'],
    },
  },
  {
    id: 'marlins-v-21',
    category: 'vocabulary',
    question_type: 'multiple_choice',
    question_text: 'What is this heavy iron mooring device called, shown in the image?',
    options: ['Anchor', 'Rudder', 'Propeller', 'Helm'],
    correct_answer: 'Anchor',
    order_number: 21,
    is_active: true,
    level: 'A1',
    audio_url: null,
    image_url: 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=600&h=350&fit=crop',
    pronunciation_text: null,
    question_data: {
      hint: 'A heavy forged metal device attached to a chain used to hold a vessel fast to the seabed.',
    },
  },
  {
    id: 'marlins-v-22',
    category: 'vocabulary',
    question_type: 'multiple_choice',
    question_text: 'In cruise hospitality and maritime safety, what does "Muster Station" mean?',
    options: [
      'The designated assembly area where passengers and crew gather during an emergency',
      'The central dining room where breakfast is served',
      'The luggage sorting area in the terminal building',
      'The crew recreation lounge on Deck 2'
    ],
    correct_answer: 'The designated assembly area where passengers and crew gather during an emergency',
    order_number: 22,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-v-23',
    category: 'vocabulary',
    question_type: 'multiple_choice',
    question_text: 'What is the nautical term for the right-hand side of a ship when facing forward toward the bow?',
    options: ['Starboard', 'Port', 'Bow', 'Stern'],
    correct_answer: 'Starboard',
    order_number: 23,
    is_active: true,
    level: 'A1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-v-24',
    category: 'vocabulary',
    question_type: 'multiple_choice',
    question_text: 'What is the nautical term for the left-hand side of a ship when facing forward toward the bow?',
    options: ['Port', 'Starboard', 'Aft', 'Bridge'],
    correct_answer: 'Port',
    order_number: 24,
    is_active: true,
    level: 'A1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-v-25',
    category: 'vocabulary',
    question_type: 'multiple_choice',
    question_text: 'What is the kitchen on board a ship called?',
    options: ['Galley', 'Pantry', 'Messroom', 'Stateroom'],
    correct_answer: 'Galley',
    order_number: 25,
    is_active: true,
    level: 'A1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-v-26',
    category: 'vocabulary',
    question_type: 'multiple_choice',
    question_text: 'What does "USPH" stand for in cruise ship sanitation and public health inspection standards?',
    options: [
      'United States Public Health',
      'Universal Ship Passenger Hospital',
      'United Seafarers Protection Health',
      'Undersea Protection and Safety Harbor'
    ],
    correct_answer: 'United States Public Health',
    order_number: 26,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-v-27',
    category: 'vocabulary',
    question_type: 'multiple_choice',
    question_text: 'In hotel and housekeeping service, what does a "DND" door sign mean?',
    options: [
      'Do Not Disturb',
      'Day and Night Duty',
      'Daily Neat Deck',
      'Door Not Delivered'
    ],
    correct_answer: 'Do Not Disturb',
    order_number: 27,
    is_active: true,
    level: 'A1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-v-28',
    category: 'vocabulary',
    question_type: 'multiple_choice',
    question_text: 'What is a "Gangway"?',
    options: [
      'A movable ramp or walkway used by passengers and crew to embark or disembark the ship',
      'The narrow corridor between crew cabins',
      'The emergency exit ladder inside the engine room',
      'The anchor windlass control platform'
    ],
    correct_answer: 'A movable ramp or walkway used by passengers and crew to embark or disembark the ship',
    order_number: 28,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-v-29',
    category: 'vocabulary',
    question_type: 'multiple_choice',
    question_text: 'Which item is the primary tool used to quickly smother a small grease fire on a galley cooking pan?',
    options: ['Fire blanket and wet chemical extinguisher', 'Water bucket', 'Electric fan blower', 'Paper napkins'],
    correct_answer: 'Fire blanket and wet chemical extinguisher',
    order_number: 29,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-v-30',
    category: 'vocabulary',
    question_type: 'multiple_choice',
    question_text: 'What is the "Tender Boat" used for when a cruise ship is anchored offshore?',
    options: [
      'Transporting passengers between the anchored ship and the harbor pier',
      'Towing large container barges into the river',
      'Pumping fresh drinking water into the ship tanks',
      'Carrying heavy maintenance spare parts to the rudder'
    ],
    correct_answer: 'Transporting passengers between the anchored ship and the harbor pier',
    order_number: 30,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },

  // ==========================================
  // SECTION 3: TIME & NUMBERS (10 QUESTIONS)
  // ==========================================
  {
    id: 'marlins-tn-31',
    category: 'time_and_numbers',
    question_type: 'multiple_choice',
    question_text: 'A guest asks what time the dinner reservation is. Look at the clock in the picture. Which time is shown?',
    options: ['7:30 PM (19:30)', '8:00 PM (20:00)', '6:15 PM (18:15)', '9:45 PM (21:45)'],
    correct_answer: '7:30 PM (19:30)',
    order_number: 31,
    is_active: true,
    level: 'A1',
    audio_url: null,
    image_url: 'https://images.unsplash.com/photo-1501139083538-0139583c060f?w=500&h=350&fit=crop',
    pronunciation_text: null,
    question_data: {
      hint: 'Look at the hour and minute hands on the clock face.',
    },
  },
  {
    id: 'marlins-tn-32',
    category: 'time_and_numbers',
    question_type: 'multiple_choice',
    question_text: 'How is the military time "20:30" expressed in the 12-hour clock standard?',
    options: ['8:30 PM', '8:30 AM', '10:30 PM', '7:30 PM'],
    correct_answer: '8:30 PM',
    order_number: 32,
    is_active: true,
    level: 'A1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-tn-33',
    category: 'time_and_numbers',
    question_type: 'gap_fill',
    question_text: 'Complete the daily cruise schedule with the correct times and capacity numbers.',
    correct_answer: '7:00 AM,150',
    order_number: 33,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      text_template: 'Breakfast starts at {0} in the Lido Cafe. The morning shore excursion accommodates a maximum of {1} guests.',
      gaps: [
        { index: 0, correct: '7:00 AM', options: ['7:00 AM', '8:00 AM', '9:00 AM', '10:00 AM'] },
        { index: 1, correct: '150', options: ['100', '150', '200', '250'] },
      ],
    },
  },
  {
    id: 'marlins-tn-34',
    category: 'time_and_numbers',
    question_type: 'multiple_choice',
    question_text: 'The evening buffet starts at 18:45 and closes at 21:15. How long is the buffet open?',
    options: ['2 hours and 30 minutes', '2 hours and 15 minutes', '3 hours', '1 hour and 45 minutes'],
    correct_answer: '2 hours and 30 minutes',
    order_number: 34,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-tn-35',
    category: 'time_and_numbers',
    question_type: 'multiple_choice',
    question_text: 'A cabin steward has 16 staterooms to clean. Each stateroom takes 15 minutes. How many total hours will it take to clean all cabins?',
    options: ['4 hours', '3 hours and 30 minutes', '5 hours', '2 hours and 45 minutes'],
    correct_answer: '4 hours',
    order_number: 35,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-tn-36',
    category: 'time_and_numbers',
    question_type: 'multiple_choice',
    question_text: 'How do you say the cabin number "7042" in English standard maritime radiotelephony (SMCP)?',
    options: [
      'Seven – zero – four – two',
      'Seventy – forty-two',
      'Seven thousand and forty-two',
      'Seven hundred forty-two'
    ],
    correct_answer: 'Seven – zero – four – two',
    order_number: 36,
    is_active: true,
    level: 'A1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-tn-37',
    category: 'time_and_numbers',
    question_type: 'multiple_choice',
    question_text: 'There are 2,400 passengers on board. 60% of them book a shore excursion. How many passengers go on the tour?',
    options: ['1,440 passengers', '1,200 passengers', '1,600 passengers', '1,800 passengers'],
    correct_answer: '1,440 passengers',
    order_number: 37,
    is_active: true,
    level: 'B1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-tn-38',
    category: 'time_and_numbers',
    question_type: 'multiple_choice',
    question_text: 'A dinner bill comes to $85.00. The guest gives a 15% gratuity tip. How much is the tip amount?',
    options: ['$12.75', '$10.50', '$15.00', '$8.50'],
    correct_answer: '$12.75',
    order_number: 38,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-tn-39',
    category: 'time_and_numbers',
    question_type: 'multiple_choice',
    question_text: 'What is the correct English word for the ordinal number "22nd"?',
    options: ['Twenty-second', 'Twenty-two', 'Twentieth-two', 'Twelfth-second'],
    correct_answer: 'Twenty-second',
    order_number: 39,
    is_active: true,
    level: 'A1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-tn-40',
    category: 'time_and_numbers',
    question_type: 'multiple_choice',
    question_text: 'The IMO standard General Emergency Alarm signal on the ship whistle consists of _______ short blasts followed by one prolonged blast.',
    options: ['Seven (7)', 'Three (3)', 'Five (5)', 'Ten (10)'],
    correct_answer: 'Seven (7)',
    order_number: 40,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },

  // ==========================================
  // SECTION 4: READING (10 QUESTIONS)
  // ==========================================
  {
    id: 'marlins-r-41',
    category: 'reading_comprehension',
    question_type: 'paragraph_title_match',
    question_text: 'The following text has three paragraphs. Choose the correct title for each paragraph from the options. There is one title you do not need.',
    correct_answer: 'The psychological cause of seasickness.,The unwanted effects of medication.,Helpful drug-free remedies.',
    order_number: 41,
    is_active: true,
    level: 'B1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      article_title: 'SEASICKNESS AND MOTION DISCOMFORT.',
      titles: [
        'The psychological cause of seasickness.',
        'The unwanted effects of medication.',
        'Helpful drug-free remedies.',
        'Why children rarely get seasick.'
      ],
      paragraphs: [
        {
          id: 'p1',
          text: 'Seasickness is not only caused by rough seas. Scientific studies have shown that some people become seasick by suggestion. They simply convince themselves that being on a ship will make them ill. On the other hand, for those who can forget about it, seasickness is often not a problem.',
        },
        {
          id: 'p2',
          text: 'One of the most widely recommended drug remedies is a scopolamine patch applied behind the ear at least eight hours before exposure, with effectiveness for up to three days. However, the patch can cause side effects such as dry mouth, blurry vision, drowsiness, and dizziness.',
        },
        {
          id: 'p3',
          text: 'Some say that ginger or eating green apples can help to prevent nausea without drowsiness. Another suggestion is to wear an acupressure wristband, which has a plastic bead that presses against the pressure point on the palm side of the wrist.',
        },
      ],
      correct_matches: {
        p1: 'The psychological cause of seasickness.',
        p2: 'The unwanted effects of medication.',
        p3: 'Helpful drug-free remedies.',
      },
    },
  },
  {
    id: 'marlins-r-42',
    category: 'reading_comprehension',
    question_type: 'multiple_choice',
    question_text: 'Based on the seasickness passage above, when should a motion sickness patch be applied for best effectiveness?',
    options: [
      'At least eight hours before exposure to rough sea',
      'Only after you start feeling dizzy and nauseous',
      'Three days after boarding the cruise vessel',
      'Immediately before going to sleep at midnight'
    ],
    correct_answer: 'At least eight hours before exposure to rough sea',
    order_number: 42,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-r-43',
    category: 'reading_comprehension',
    question_type: 'multiple_choice',
    question_text: 'According to the passage, what natural food items are suggested to prevent seasickness without causing drowsiness?',
    options: [
      'Ginger and green apples',
      'Hot milk and dark chocolate',
      'Citrus fruits and bread',
      'Raw fish and ginger ale'
    ],
    correct_answer: 'Ginger and green apples',
    order_number: 43,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-r-44',
    category: 'reading_comprehension',
    question_type: 'paragraph_title_match',
    question_text: 'FIRE SAFETY ON BOARD - Match each paragraph with its correct title. There is one title you do not need.',
    correct_answer: 'What to do when you discover a fire.,Evacuation procedures for passengers.,Prevention is better than cure.',
    order_number: 44,
    is_active: true,
    level: 'B1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      article_title: 'FIRE SAFETY ON BOARD CRUISE SHIPS.',
      titles: [
        'What to do when you discover a fire.',
        'Evacuation procedures for passengers.',
        'Prevention is better than cure.',
        'Using heavy foam hoses only.'
      ],
      paragraphs: [
        {
          id: 'p1',
          text: 'If you see smoke or flames, immediately sound the alarm by breaking the nearest call point glass. Phone the bridge on the emergency number, state your name, location, and the nature of the fire.',
        },
        {
          id: 'p2',
          text: 'When the emergency alarm sounds, direct all guests to their designated muster stations. Ensure everyone has their lifejacket on and that fire doors are kept shut to stop smoke spreading.',
        },
        {
          id: 'p3',
          text: 'Never use electrical appliances with damaged cords in staterooms. Ensure all galley fryers are monitored and that cigarette disposal bins are emptied into fire-proof containers regularly.',
        },
      ],
      correct_matches: {
        p1: 'What to do when you discover a fire.',
        p2: 'Evacuation procedures for passengers.',
        p3: 'Prevention is better than cure.',
      },
    },
  },
  {
    id: 'marlins-r-45',
    category: 'reading_comprehension',
    question_type: 'gap_fill',
    question_text: 'CABIN SERVICE INFORMATION - Read the text and fill in the missing blanks.',
    correct_answer: 'available,delivered,charge,contact',
    order_number: 45,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      text_template: 'Room service is {0} 24 hours a day. Orders placed before 11 PM will be {1} within 30 minutes. There is no extra {2} for continental breakfast. For special dietary requirements, please {3} the reception desk.',
      gaps: [
        { index: 0, correct: 'available', options: ['available', 'open', 'ready', 'free'] },
        { index: 1, correct: 'delivered', options: ['delivered', 'cooked', 'prepared', 'served'] },
        { index: 2, correct: 'charge', options: ['charge', 'cost', 'price', 'money'] },
        { index: 3, correct: 'contact', options: ['contact', 'visit', 'call', 'reach'] },
      ],
    },
  },
  {
    id: 'marlins-r-46',
    category: 'reading_comprehension',
    question_type: 'gap_fill',
    question_text: 'THINGS YOU SHOULD NOT PACK FOR A CRUISE - Read the text and choose the correct words.',
    correct_answer: 'banned,pack,iron,exception',
    order_number: 46,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {
      text_template: 'Certain items are {0} on cruise ships due to maritime fire regulations. Do not {1} a travel {2} in your suitcase. The only {3} is grooming items such as hair straighteners with auto shut-off.',
      gaps: [
        { index: 0, correct: 'banned', options: ['banned', 'allowed', 'available', 'popular'] },
        { index: 1, correct: 'pack', options: ['pack', 'buy', 'order', 'leave'] },
        { index: 2, correct: 'iron', options: ['iron', 'blanket', 'pillow', 'towel'] },
        { index: 3, correct: 'exception', options: ['exception', 'rule', 'problem', 'danger'] },
      ],
    },
  },
  {
    id: 'marlins-r-47',
    category: 'reading_comprehension',
    question_type: 'multiple_choice',
    question_text: 'Read the safety sign: "EMERGENCY ESCAPE ROUTE - KEEP CLEAR AT ALL TIMES". What does this sign require crew members to do?',
    options: [
      'Ensure the corridor and stairs are never blocked by luggage, service carts, or cleaning gear',
      'Only use this door when delivering room service breakfast',
      'Lock the door at night to maintain passenger cabin quietness',
      'Clean the door glass panels every afternoon'
    ],
    correct_answer: 'Ensure the corridor and stairs are never blocked by luggage, service carts, or cleaning gear',
    order_number: 47,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-r-48',
    category: 'reading_comprehension',
    question_type: 'multiple_choice',
    question_text: 'Read the passenger announcement: "All guests booked for the Mayan Ruins tour must assemble in the Starlight Lounge on Deck 6 by 08:30 with their shore passes ready." What must guests bring to the lounge?',
    options: ['Their shore passes', 'Their heavy suitcases', 'Their cabin lifejackets', 'Their passports only'],
    correct_answer: 'Their shore passes',
    order_number: 48,
    is_active: true,
    level: 'A1',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-r-49',
    category: 'reading_comprehension',
    question_type: 'multiple_choice',
    question_text: 'Read the galley memo: "Gluten-free bread is stored separately in the bakery pantry to avoid cross-contamination." Why is it stored in a separate dedicated area?',
    options: [
      'To prevent contact with gluten flour and protect guests with severe allergies',
      'Because gluten-free bread spoils faster than normal bread',
      'To keep it hot before the dinner service starts',
      'Because it is only served to the Captain and Senior Officers'
    ],
    correct_answer: 'To prevent contact with gluten flour and protect guests with severe allergies',
    order_number: 49,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },
  {
    id: 'marlins-r-50',
    category: 'reading_comprehension',
    question_type: 'multiple_choice',
    question_text: 'Read the shipboard security rule: "All crew must swipe their SeaPass cards at the security gangway when boarding or leaving the ship in every port." What is the main purpose of this procedure?',
    options: [
      'To maintain an exact head count of all personnel on board for maritime safety before sailing',
      'To track how much money crew members spend in port',
      'To check whether the crew uniform is clean',
      'To verify work visas with local port immigration'
    ],
    correct_answer: 'To maintain an exact head count of all personnel on board for maritime safety before sailing',
    order_number: 50,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: null,
    question_data: {},
  },

  // ==========================================
  // SECTION 5: LISTENING & COMMUNICATION (10 QUESTIONS)
  // ==========================================
  {
    id: 'marlins-l-51',
    category: 'listening_comprehension',
    question_type: 'image_choice',
    question_text: 'Listen to the galley order. What seafood item did the Executive Chef ask the provision master to order 85 kilos of?',
    options: [
      'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1559742811-822873691df8?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=400&fit=crop'
    ],
    correct_answer: 'Shrimp',
    order_number: 51,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: 'Provision master, for this week gala dinner we need to order 85 kilos of fresh jumbo shrimp, please confirm with supplier.',
    question_data: {
      option_type: 'image',
      option_labels: ['Shrimp', 'Lobster', 'Crab', 'Salmon'],
      audio_transcript: 'Provision master, for this week gala dinner we need to order 85 kilos of fresh jumbo shrimp, please confirm with supplier.',
    },
  },
  {
    id: 'marlins-l-52',
    category: 'listening_comprehension',
    question_type: 'image_choice',
    question_text: 'Listen to the breakfast order. What has the passenger ordered from room service?',
    options: [
      'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=400&h=400&fit=crop'
    ],
    correct_answer: 'Omelette with salad',
    order_number: 52,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: 'Good morning room service. I would like a cheese and mushroom omelette with a side green salad and a glass of orange juice to Cabin 6012.',
    question_data: {
      option_type: 'image',
      option_labels: ['Omelette with salad', 'Curry with rice', 'Toast with butter', 'Fresh fruit platter'],
      audio_transcript: 'Good morning room service. I would like a cheese and mushroom omelette with a side green salad and a glass of orange juice to Cabin 6012.',
    },
  },
  {
    id: 'marlins-l-53',
    category: 'listening_comprehension',
    question_type: 'audio_listening',
    question_text: 'Listen to the guest request. What does the passenger want the cabin steward to bring?',
    options: [
      'Two extra pillows and a bottle of mineral water',
      'Two bath towels and extra shampoo',
      'A breakfast tray and hot black coffee',
      'An iron and ironing board'
    ],
    correct_answer: 'Two extra pillows and a bottle of mineral water',
    order_number: 53,
    is_active: true,
    level: 'A1',
    audio_url: 'https://xekfarqemnyfguxtpeoj.supabase.co/storage/v1/object/public/marlint-audio/listening/q26_pillow_request.mp3',
    image_url: null,
    pronunciation_text: 'Excuse me steward, could you please bring two extra pillows and a large bottle of mineral water to Cabin 8124?',
    question_data: {
      audio_transcript: 'Excuse me steward, could you please bring two extra pillows and a large bottle of mineral water to Cabin 8124?',
    },
  },
  {
    id: 'marlins-l-54',
    category: 'listening_comprehension',
    question_type: 'audio_listening',
    question_text: 'Listen to the Captain’s public address from the Bridge. What is the expected weather condition tomorrow morning?',
    options: [
      'Moderate seas with wind speeds up to 25 knots',
      'A severe tropical storm with 60-knot hurricane winds',
      'Completely calm seas and sunny skies all day',
      'Dense fog with zero visibility'
    ],
    correct_answer: 'Moderate seas with wind speeds up to 25 knots',
    order_number: 54,
    is_active: true,
    level: 'B1',
    audio_url: null,
    image_url: null,
    pronunciation_text: 'Good evening ladies and gentlemen, this is the Captain speaking from the Bridge. We are currently cruising smoothly, but tomorrow morning we expect moderate seas and wind speeds up to 25 knots.',
    question_data: {
      audio_transcript: 'Good evening ladies and gentlemen, this is the Captain speaking from the Bridge. We are currently cruising smoothly, but tomorrow morning we expect moderate seas and wind speeds up to 25 knots.',
    },
  },
  {
    id: 'marlins-l-55',
    category: 'listening_comprehension',
    question_type: 'audio_listening',
    question_text: 'Listen to the Restaurant Manager’s briefing. What is the special chef dessert for tonight’s Gala Dinner?',
    options: [
      'Warm chocolate lava cake with vanilla ice cream',
      'Lemon cheesecake with blueberry coulis',
      'Fresh tropical fruit salad with sorbet',
      'Tiramisu with roasted hazelnuts'
    ],
    correct_answer: 'Warm chocolate lava cake with vanilla ice cream',
    order_number: 55,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: 'Team, for tonight’s Gala Dinner, our chef’s special dessert is warm chocolate lava cake served with Tahitian vanilla ice cream.',
    question_data: {
      audio_transcript: 'Team, for tonight’s Gala Dinner, our chef’s special dessert is warm chocolate lava cake served with Tahitian vanilla ice cream.',
    },
  },
  {
    id: 'marlins-l-56',
    category: 'listening_comprehension',
    question_type: 'audio_listening',
    question_text: 'Listen to the Safety Officer’s drill command. What must all crew members wear when reporting to muster stations?',
    options: [
      'Lifejackets, long pants, and closed-toe safety shoes',
      'Flashlights, warm blankets, and swimming goggles',
      'Identification badges and luggage bags only',
      'Fire extinguishers and emergency radios'
    ],
    correct_answer: 'Lifejackets, long pants, and closed-toe safety shoes',
    order_number: 56,
    is_active: true,
    level: 'A2',
    audio_url: 'https://xekfarqemnyfguxtpeoj.supabase.co/storage/v1/object/public/marlint-audio/listening/q9_safety_drill.mp3',
    image_url: null,
    pronunciation_text: 'Attention all crew, this is a drill. Report immediately to your designated muster stations wearing your lifejackets, long pants, and closed-toe safety shoes.',
    question_data: {
      audio_transcript: 'Attention all crew, this is a drill. Report immediately to your designated muster stations wearing your lifejackets, long pants, and closed-toe safety shoes.',
    },
  },
  {
    id: 'marlins-l-57',
    category: 'listening_comprehension',
    question_type: 'audio_listening',
    question_text: 'Listen to the bar customer. What drinks did the guest order from the bar waiter?',
    options: [
      'An iced cappuccino with oat milk and sparkling water with lemon',
      'A hot latte with almond milk and still mineral water',
      'A strawberry smoothie and black iced coffee',
      'A glass of fresh orange juice and tonic water'
    ],
    correct_answer: 'An iced cappuccino with oat milk and sparkling water with lemon',
    order_number: 57,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: 'Hi there, I would like one iced cappuccino with oat milk, and a glass of sparkling water with lemon, please.',
    question_data: {
      audio_transcript: 'Hi there, I would like one iced cappuccino with oat milk, and a glass of sparkling water with lemon, please.',
    },
  },
  {
    id: 'marlins-l-58',
    category: 'listening_comprehension',
    question_type: 'audio_listening',
    question_text: 'Listen to the VHF maritime radio transmission. What is the pilot vessel instruction to the cruise ship navigation bridge?',
    options: [
      'Reduce speed to 6 knots and rig pilot ladder on the port side',
      'Increase speed to 12 knots and alter course to starboard',
      'Drop port anchor immediately outside the breakwater',
      'Maintain course and standby on VHF Channel 16'
    ],
    correct_answer: 'Reduce speed to 6 knots and rig pilot ladder on the port side',
    order_number: 58,
    is_active: true,
    level: 'B1',
    audio_url: null,
    image_url: null,
    pronunciation_text: 'Cruise Vessel Pacific Star, this is Port Pilot Station. Reduce speed to six knots and prepare pilot ladder on the port side, one meter above the water line.',
    question_data: {
      audio_transcript: 'Cruise Vessel Pacific Star, this is Port Pilot Station. Reduce speed to six knots and prepare pilot ladder on the port side, one meter above the water line.',
    },
  },
  {
    id: 'marlins-l-59',
    category: 'listening_comprehension',
    question_type: 'audio_listening',
    question_text: 'Listen to the passenger inquiry at the Front Desk. What time does the duty-free jewelry store open?',
    options: ['At 19:00 (7:00 PM)', 'At 17:00 (5:00 PM)', 'At 20:30 (8:30 PM)', 'At 09:00 AM tomorrow'],
    correct_answer: 'At 19:00 (7:00 PM)',
    order_number: 59,
    is_active: true,
    level: 'A1',
    audio_url: null,
    image_url: null,
    pronunciation_text: 'Good afternoon. The duty-free shops on Deck 5, including the jewelry store, will open at 19:00 once we are in international waters.',
    question_data: {
      audio_transcript: 'Good afternoon. The duty-free shops on Deck 5, including the jewelry store, will open at 19:00 once we are in international waters.',
    },
  },
  {
    id: 'marlins-l-60',
    category: 'listening_comprehension',
    question_type: 'audio_listening',
    question_text: 'Listen to the shore announcement. What time is the last tender boat returning from the Santorini harbor pier?',
    options: ['17:30 (5:30 PM)', '18:00 (6:00 PM)', '16:45 (4:45 PM)', '17:00 (5:00 PM)'],
    correct_answer: '17:30 (5:30 PM)',
    order_number: 60,
    is_active: true,
    level: 'A2',
    audio_url: null,
    image_url: null,
    pronunciation_text: 'Attention all guests ashore in Santorini. The last tender boat will depart the harbor pier at 17:30 sharp. The ship will weigh anchor at 18:00.',
    question_data: {
      audio_transcript: 'Attention all guests ashore in Santorini. The last tender boat will depart the harbor pier at 17:30 sharp. The ship will weigh anchor at 18:00.',
    },
  },
];
